# Define wall1
[world.wall1.body]
type = "box"
size = [0.05, 5.0, 2.0]


# Define wall2
[world.wall2.body]
type = "box"
size = [0.05, 5.0, 2.0]


# Define wall3
[world.wall3.body]
type = "box"
size = [0.05, 5.0, 2.0]


# Define wall4
[world.wall4.body]
type = "box"
size = [0.05, 5.0, 2.0]


# Define wall5
[world.wall5.body]
type = "box"
size = [0.05, 5.0, 2.0]


# Define wall6
[world.wall6.body]
type = "box"
size = [0.05, 5.0, 2.0]

# Define wall7
[world.wall7.body]
type = "box"
size = [0.05, 20.0, 2.0]


# Define table 1
[world.table1.body]
type = "box"
size = [0.75, 1.4, 0.05]
april-tags = [{id = 1, pose = {xy = [0.375, -0.6]}},
              {id = 2, pose = {xy = [0.375, 0.6]}}]

# Define table 2
[world.table2.body]
type = "box"
size = [0.86, 1.78, 0.05]
april-tags = [{id = 3, pose = {xy = [0.43, -0.6]}},
              {id = 4, pose = {xy = [0.43, 0.6]}}]

# Define a package
[world.package.body]
type = "box"
size = [0.32, 0.28, 0.3]
mass = 0.1
friction = [2,2,2]
april-tags = [{id = 5, pose = {xyz = [0.16, 0.0, 0.0]}},
              {id = 6, pose = {axyzd = [180, -0.16, 0.0, 0.0]}}]


# Models in the scene
[[model-list]]
model = "robot"
pose = {axyzd = [0, 1, 0, 1.0]}



# First Room

# Add a wall
[[model-list]]
model = "wall1"
pose = {axyzd = [90.0, 1.5, -2.5, 1.0]}
fixed = true
color = "silver"



[[model-list]]
model = "wall2"
pose = {axyzd = [90.0, 1.5, 2.5, 1.0]}
fixed = true
color = "silver"

[[model-list]]
model = "wall3"
pose = {axyzd = [0, -1, 0, 1.0]}
fixed = true
color = "silver"

# Add table in front of the robot and rotate so the AprilTags are facing the robot.
[[model-list]]
model = "table1"
pose = {rpyxyzd = [0, 0, 180, 3.0, 0, 1]}
fixed = true
color = "dimgray"

# Add box on top of table in front of the robot.
[[model-list]]
model = "package"
pose = {rpyxyzd = [0, 0, 180, 2.7, 0, 1.3]}


# Second Room

[[model-list]]
model = "wall4"
pose = {axyzd = [90.0, 1.5, 7.5, 1.0]}
fixed = true
color = "silver"

[[model-list]]
model = "wall5"
pose = {axyzd = [90.0, 1.5, 12.5, 1.0]}
fixed = true
color = "silver"

[[model-list]]
model = "wall6"
pose = {axyzd = [0, -1, 10, 1.0]}
fixed = true
color = "silver"

# Add table in front of the robot and rotate so the AprilTags are facing the robot.
[[model-list]]
model = "table2"
pose = {rpyxyzd = [0, 0, 0, 4, 10, 0.76]}
fixed = true
color = "saddlebrown"


# Third wall

[[model-list]]
model = "wall7"
pose = {axyzd = [0, 8, 5, 1.0]}
fixed = true
color = "silver"